### PR TITLE
feat: corrected CI tests to run  against on all commits

### LINKED ISSUE #22: Preview deploy tests should run on main commit as well as pull request
**Describe the bug**
Currently [tests are only run against preview deploy on pull_request](https://github.com/ambianic/ambianic-subscriptions/blob/3d9c15b39721ee426f8141ba0bc57992e27fa09c/.github/workflows/ci.yml#L35). 

**Desired behavior***
Tests should run for main commits as well. See [ambianic-ui workflow.](https://github.com/ambianic/ambianic-ui/blob/040b902d21d15473aa87b145ccbcbddd80c6862e/.github/workflows/lighthouse.yml#L17)

### PR DESCRIPTION
**Pull request by vickywane**
This PR would fix [this issue](https://github.com/ambianic/ambianic-subscriptions/issues/22).

This pull request removes the `if` condition from the `Run tests against deployed preview` step within the workflow file for this API's CI.

### CODE REVIEW

**Review by ivelin — APPROVED** [review]

**Comment by ivelin** [comment]
@vickywane this is not a feature. Do not mark PRs as a "feat:" . Use the appropriate prefix based on the semantic release conventions:
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#type

In this case the prefix should be "ci: ".

**Comment by vickywane** [comment]
@ivelin That correction has been made.

**Review by ivelin — CHANGES_REQUESTED** [review]
This is not a feature. Use correct prefix.

**Comment by vickywane** [comment]
I would be mindful of it. I however reworded the commit message.

**Pull request merged**
